  export const config = {
    minTokenLength: 2,
    topTermsPerSegment: 5,
    topNeighborsPerSegment: 3,
    graphSimilarityThreshold: 0.12,
    textrankDamping: 0.85,
    textrankIterations: 30,
    redundancyThreshold: 0.70,
    maxOutputSegments: 30,
    importanceWeights: {
      textRank: 0.30,
      tfidf: 0.15,
      decision: 0.12,
      requirement: 0.10,
      constraint: 0.08,
      failure: 0.08,
      nextStep: 0.08,
      recency: 0.05
    },
    fillerPhrases: [
      "thanks",
      "thank you",
      "okay",
      "ok",
      "sure",
      "you're welcome",
      "sounds good"
    ],
    stopWords: [
      "a",
      "about",
      "after",
      "all",
      "also",
      "am",
      "an",
      "and",
      "any",
      "are",
      "as",
      "at",
      "be",
      "because",
      "been",
      "before",
      "being",
      "between",
      "both",
      "but",
      "by",
      "can",
      "could",
      "did",
      "do",
      "does",
      "doing",
      "done",
      "down",
      "each",
      "even",
      "for",
      "from",
      "further",
      "had",
      "has",
      "have",
      "having",
      "he",
      "her",
      "here",
      "hers",
      "him",
      "his",
      "how",
      "if",
      "in",
      "into",
      "is",
      "it",
      "its",
      "just",
      "let",
      "me",
      "more",
      "most",
      "my",
      "no",
      "nor",
      "not",
      "now",
      "of",
      "off",
      "on",
      "once",
      "only",
      "or",
      "other",
      "our",
      "out",
      "over",
      "own",
      "same",
      "she",
      "should",
      "so",
      "some",
      "such",
      "than",
      "that",
      "the",
      "their",
      "them",
      "then",
      "there",
      "these",
      "they",
      "this",
      "those",
      "through",
      "to",
      "too",
      "under",
      "until",
      "up",
      "very",
      "was",
      "we",
      "were",
      "what",
      "when",
      "where",
      "which",
      "while",
      "who",
      "why",
      "will",
      "with",
      "would",
      "you",
      "your"
    ],
    artifactPatterns: [
      /^copy code$/i,
      /^share$/i,
      /^edit$/i,
      /^regenerate$/i
    ],
    criticalCuePatterns: [
      /\bmust\b/i,
      /\bneed\b/i,
      /\brequired\b/i,
      /\bshould\b/i,
      /\bdon't\b/i,
      /\bdo not\b/i,
      /\bcannot\b/i,
      /\bcan't\b/i,
      /\bwithout\b/i,
      /\bfailed\b/i,
      /\berror\b/i,
      /\bdecid/i,
      /\bswitch to\b/i,
      /\bgo with\b/i,
      /\bnext step\b/i,
      /\btodo\b/i
    ]
  };
